apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: repo-homepage-sync-secrets
    namespace: repo-homepage-sync
spec:
    secretTemplates:
        - name: repo-homepage-sync-secrets
          type: Opaque
          stringData:
            github-app-id: ENC[AES256_GCM,data:YmPvdzWzAQ==,iv:tFMCAdVeDby2qTNEyj71BP+HogYkiU2B3/vkW+CrfgM=,tag:nRDpNhcSRWQuY/5K21BfFg==,type:str]
            github-app-installation-id: ENC[AES256_GCM,data:/46Wv9YxtHFt,iv:J0XmZb6zvEG0sETcEnUD84xKg4CjWl9TDCGwgGqdYKE=,tag:7N3t1HrlDKMGs5a5TQZP/g==,type:str]
            github-app-private-key.pem: ENC[AES256_GCM,data:NnoXnO/epZy47IgYkwbvqjVjfw6gQsAU8H31kyimiQJDQroQErp9VAyh3ieX33mY5k9K5JSl0c8iLLqDkCBGjuI01tuh+QmYTvwlxiqUsnefVGcIRfKlq5r15wCXR/eD14LjBvzAafaBfn6+dPxjFzvEOHAjHHtjUNmXiYt0Cu6UErb+1qrpS5dzEyZZx/ysEOAJMrIfTDoL6E/FYba6mLn/9cfnS7Cp1PkZFq1YgK5Esn78KzmVmOf0x6eSE9I45Z2NwldQ+xo9wNW1H7tBrjtwH4+XkuwcMEpdilZYBER4btWKJ3JcsNa/qEvnc038X5oQXDs7eQFGjLiF+AAiziuU6IRbxFavP4qGK77s459WJtsw/QbWB9pVqQ3MO4c/WwD7EIuAMM3pe1dOXrVcr9rMpk54OuEcg6OY4XzlH3l6F0xZBZLh5qzx3HCBrqx9Mgg0JnZekAJVaabt4V27UjfsRvWXkf2w/TRFyIorw2eSS6POnbwozW2t7fc5FTot2ky+0tu7N3lEYp12/tYsKlulvdhtncX4zGhqfxlAKrnzRRO/0PObpklx/i1NQOSDodYfe8jFuEPP27+tFBKJhqp0jsAOorWFrcPTqP6OpItnVNDBhPOjZyzkdmXrqcLuEhJ/7x39cFF8YJblJh4WSFnazD8BIrihkH7vdl1wc9qWi3eCgqxCJfZcpiVKCAbZ6HYMNDDlNzW/hMbW6B0l+FPGH0bhRjKdbZpAjOTTpvPANLiu7BgEII3ps9zm2WK76oTHOoepmENvFRaosFmdbSY5xlYkNWVB7MPSBPsOXb8TS0Nz0q6n/SsbO2YWi0nYiQcy+cQh8sr/vtFAqMwCPNvpD4iyGUdBvg4JOkk7MxQJejovjR51KvJmzMwWnZrOldwqsu65sNLv5iA10i97M2znIMMfPDxhmntOM8HKijbIbrIzotokT6m57G1ZIqiX7tSVhFW+AYSHidcyQ2XRxLx17zgRbQVe6L4IlNbXmkloZMaj2OUoLY1ufPe8WmZEQHHuKpulThgmoDR3gq6mDzbZJF916vwQYAQH/fBmqQ5sS0W7ZLP7aIyVGjr77qA2FPWL9HGbhW3AsAG4YlHvqL3a7hCjG5rY9moE0pVU/bZl9uh0EX0sX09wCt1ruxv36kzXbi5g39G+/Eh2BY3jbE0lWQ8SmE3K9zYkVZyT462DNtbCscIqkTMPDfnYM19dbiy9bEixHEhs7r87y6h4oqV/tR1+5Qq0RH8Kf7w4crdGSrWV7p4lNNGVg7ufGpn2k7X7cGynR187ydIOs5rnyPP5KQZI5kWZCnb/n0AxsliuYNilfmfnmJW3Ank+nUwI5fz82CUhoQ+0f8Q8thqudkNJ3RESeI/DtNKjedtzAnJmCuReosMrv9QmGe4XVnrf4w5WiDO0jhsvPPsf3U+8v11JBl19v7BfECVpU7Li+YEIySinfZh+kvslbdc1ruigAiXujHdmc8Rix+yQXvGm2HkI46+1oWI6jdwILOk0whPH/E3i4GWRbmPh691Jh33DRDWjoopiQBXvEbHPFx869YwRRxHVs6xceeXM+IyWG3XT2GLQ1iSYMfr7npsNT12uMBjRZ7sk0BbsovQBq6aFOE9sp+TngALo1YEAU/bGQhumTp3tezGrqkMKBLQArKU7j6rsSRiKrZPk9d+Nzu3YFUtRSuL7c4Cv4E1YC0tM48YI4funr1a/4Wqpf270XZiDcYmdh8gamo2ybVKXn2qgJoUefZ2hrBhInVt1n5QKin3wLYgpKVXmvmn1grPrzdqBSEwX6UtPG1K7fZnnPuOcko2Tr6SxYioWootkfYwae6EWUiUFR2C84xJSaiKXkz6Pv9RwDtGMYIXrN4a1RsybHzTOcSRo3xIr9FhoJZ3kkaqZTBxmaSmbt/0dUgeIUL6+B84bkNjJe+lV35Kx8lp8v+0OkA2wP2wb+rTXdSiSlMM6JnKqRPMHbOTup9ICK3JVshvG5PD/d8n4+z+nsmPlPQzxCl3YV5Zcvu6cCbzQV/uy5yJjuCfdWrd7Y7WPOeo+M2wWHSt8YS/7+OhWRnxGXpCJCM2J5m7dEm+JXf4JEVByGSF8A3W95ReETr2r5jjon1llFQd2Iq80kq3eG1ziUtrRQ7/gGZYLPbc8A3nBWLY3cjmjY6pThjTnZ0OnN9b4755TmAKMp4gqL2+CWuUtsg2Zv9RRNvbrOuhk5NgDPsdgNczpAuMK35o/Tg==,iv:HZAgbY4PVGrn90ycBVCiU65mA6gqi3Bi33SeZPe6IoY=,tag:1TH0zr1vaoi9IDM3i+39Zw==,type:str]
sops:
    age:
        - recipient: age1tf6hky66y70lgkd9petf5tzempxltsh2kpe0nqs696ascnyyk5eqfvyyuh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNy9wN2dLbmdGKzQvKy95
            ek1LWGR5Z2dRczdiZmxXRXZVUUtsQnFwQ25BClpEWGdBYTRJVERwN2wvOUVXUGZZ
            bThCdFFEcTF4cDRNYnpxbjZnb2dqdEkKLS0tIEsyOVo1RHE4MGkyN1ViRjRtQXBB
            bjk4aDViQ1hlbWUyTEh0RGw0NUdQb2sK2aD3VxM7gDaf9V/mIui8eL6BZoTPpqB1
            4bQZTYMl0U9+jL1if48HAAzPtjrfzLiFFbZj+NGhyt1PqoMHdE6S9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDBuYmQ0Z095WXdQRGc3
            MDFGTjNLem5vU0pYUVpzV1Q0djhlVWNkUzE4CjZLeTZJREVzeVJ5ajZoLzhnY0FS
            QTdndHV1NFVubFFHV01lZ282czQ2YUUKLS0tIGU5QWJObkJJcjVSd3MrdFdqRUd4
            d1ZjQlFndkEvRXZFU1dPRUtRWnZrU3cKZoN6QkpgePX/4IbyULJi33riBQcv6Qt5
            P/78RxWcnjY24hlnd65o5T80A1vHtqjSw8LppJj7upmhegZjiEW6ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T03:49:26Z"
    mac: ENC[AES256_GCM,data:yQ6Wdt+c1p4Tdvq2VCCcSKxQXhcduAop3PevifBha+PUuBBl6aonAM0GW7eRa5dl+w2rA8cuC8O00EjP2OPWT6JOQJlVb4ioMyxE6Dx8yLnI9FCFpX+7cBkAMUIkI6S2o9JS07eoZV2QDBXGoVo8W5UAxr1hTZd7serrNxpEMMc=,iv:dCzZdLZd/EuJg3baU5yjs/HX1QZx5ZlLYNRn1VHnLrI=,tag:ZwjJdfXq6dNQXHcwBUwLrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.0
