apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: repo-homepage-sync-secrets
    namespace: repo-homepage-sync
spec:
    secretTemplates:
        - name: repo-homepage-sync-secrets
          type: Opaque
          stringData:
            github-app-id: ENC[AES256_GCM,data:bFtEL/bpDA==,iv:9XxtB0LjC6L/x7OU8wQCHwg96Uk1Js26Ju8OSkhe33o=,tag:+yF6Lq0amCoS7BbAlU51zQ==,type:str]
            github-app-installation-id: ENC[AES256_GCM,data:+mEhybh1SIyH,iv:LyHYX2s5dC8I3+QBG+U29+PREfttY8YtWNwZ35zg+SE=,tag:H5PfWr3BVCDv6C/A6+O9GQ==,type:str]
            github-app-private-key.pem: ENC[AES256_GCM,data:LFV2A4Bn0Rs0VpT/soBdUQohPzdKkRqzxgwmHHqZwQsrMW0bkHcu3i3lwKNmxrZzdRMBHvDRseILR280mdf66XlTGZiMu9kw632elKxRvUnWUQpuDctFkkhROLttJPfMk1TgNPnNU/DYMVt+myrAm6mrVZKqNYPi9WXINrRBO9A+gvZvYyLR95NCZ4UCCGXkDlnB3XguuJLGCyjnpW4a/FqjVpqoHe6HePJIfCShagOcqT5nTHG5tFHMaEfMTtJKqIvD/W4iSW46n1wLuSsI46kkGPf6TD9pIbAo9W44fRqjUavB5Jf8GM3SLPsNhWa2Y1F1LtWp9twacewyi/q0VvnXogaENamLUK490vsig17SHYBKDRuPAtgUgzFLrVgaML2u7YaT9ykgccvzOU5VNauQlD+z/IqI7VIOnEpfKnFkAyfE4xWcnD0Sc/THzdnFD5owrz5UlbdmTrfpRK8NCxwuyQXWqIO+l5Ni7Vp+7Yv+Re0ETZJOeyWABhaOqpoMsUD6IAp4PJMmoR6l2SygMDuHq6tb1JoMkjV9puzWyn7w2t0SxEmajSgqHQANsvrsZ1kL/3QMqQwtJ1JQ5OO1bwWaRDS83EGtbgJAQjfNfmCPayOVfoQtvkaMIlF4m97rAVQlK1kBNUt9DePLf+aOfiFB8xFRG09+AsuYR6UQru8k8MDLk9PDGmf/sZjdSBQIi1i+iNx61/DIynh3h/bM8lorLg5RNceStWpU1+gfHAwICzYgZ0pcuuxHF52qqZuD1z1JGhijl4fceWHeCWrfiplCd9ReLEMGOzc75lsHhSMIxopicqny+I249c+BCUsM4rdgk0aptLcOjvn8B9Jk7tVsrmYo183j3+LM+xxQ57urfwvyD6o+88EFOYHopHklaNQM2HeABgM7S6DJBNtRSp5L9CXOFdXF7kwI0etx9VuWFQIyPfJnn4BSZ9F2NMzEkXpaLw2zrV3Tcul49g/frcwRYcXcyEE1XoF38RtL7Xkyc+Q6A/6ZajvKf1HpGgLivrf8sqJEiQDe6syy6tEYlwuEp6ybe2vLu00+yfILttku/wBJ0gWqGtu8V2GrU0zeMJM3ZUtLfC7NW1XveQqsNP4mfGrajIbkLqQuVaDUUjJAbLb6vUyXkeIxCpbyfJLIH7pK8s73HgXnIj7twjS0Q5DrBWiw/A8ZyP0Mj5ekK4F2plITWo+WZLTyHk2++8DGAZT9CxW+jznZ0hHSQ9ebX29Lmbb+cLF27Byl9/HvzJd9TpFRy2kYjmYGxcJIVqJpnZKBDOOLu7sfEvdGZyRqg4l6zb6StVdh6G59i1dtT6C0ki6Um1huWt0vUs23OLLUVo6pEZdDNDvqRK9s7yjLyE63XQ+veLuxh0jx3jOIc9WZ0Df7kqhgP8FHWpRbt8gsHMymPfi7kFrhNUYmLsAkKDMdIYecgdqYbxZftl1SYqvvYqPSyHoOaPvLc1MsywD0TmGSGf+OZ9WyIjzn4vueFSvqjAH6PQtm4JSfMu5WyWaBmQvUdnL96+Pij968pc8hl3S/FTZEQrPSG54VhPuR9Tfb1p1tvNbbqpv+bAP2fr+vWGYsz3t/xeoETzAFdRjFH5tC0cVIAgxlF7HkSo25KEgeh8xsfbr4TcrccaBOZiI414Rae2uOqzzQxuqKIwbyLip2mIteKzf3FQJv2w2viBXf6SAtgN33WNxNVWMI+GH3oyyMfJAvWX5aj3xmJdl05VnX/OyvSS1pFpT/1WHu/uwO5k5abwvKsP8NKNiFJgucarsSskM+rlk21ubWQiEbuqf4UFhMp9x1KIp9kTPKODa/xRDpzERz+ZaH7TAD8hIKE8fsy1Af1VRyvlK2z8nzcmRxnMnVaPf9z8dWCCuMSxkqheMDNlSjq/rQLaLhHQMfMINSmDt6TZvJTNJWVzQhdc3LWt/QxxRt5EOwbbgZ+V8pVddYVZq8Dhnm9n+os2Mjhqj503a8MCevmJCIZL8VBRSFIYznOXXg2qxp32el1WbEJFIVBwmtIZ9rTGTYRlenIJOAfTF5hxC+bu+WDPwMbK3MbYb2Mzt1iibqZlrZbPwXh7NhBIhekhpdVY4SjmzlRvJHvHw1tAFkSfQdpusowkdDZ/Xov4tnGn6nZc0Dl7REZxabnX3Hyy6+p2C7L4awoApbrtOo18BjiGLp3VcF1cPdRh4Us5tfZ5OaEN+xWg8A/V0kWQq6M8naXvZ0MxsleY1sqJjP8U2NDA==,iv:E43Yucckj/aXeBCTNNNPlSthVeITh2lSy0fotT0Nmb8=,tag:Ng5eG0CDSggn+rE34GHRIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNy9wN2dLbmdGKzQvKy95
            ek1LWGR5Z2dRczdiZmxXRXZVUUtsQnFwQ25BClpEWGdBYTRJVERwN2wvOUVXUGZZ
            bThCdFFEcTF4cDRNYnpxbjZnb2dqdEkKLS0tIEsyOVo1RHE4MGkyN1ViRjRtQXBB
            bjk4aDViQ1hlbWUyTEh0RGw0NUdQb2sK2aD3VxM7gDaf9V/mIui8eL6BZoTPpqB1
            4bQZTYMl0U9+jL1if48HAAzPtjrfzLiFFbZj+NGhyt1PqoMHdE6S9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tf6hky66y70lgkd9petf5tzempxltsh2kpe0nqs696ascnyyk5eqfvyyuh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDBuYmQ0Z095WXdQRGc3
            MDFGTjNLem5vU0pYUVpzV1Q0djhlVWNkUzE4CjZLeTZJREVzeVJ5ajZoLzhnY0FS
            QTdndHV1NFVubFFHV01lZ282czQ2YUUKLS0tIGU5QWJObkJJcjVSd3MrdFdqRUd4
            d1ZjQlFndkEvRXZFU1dPRUtRWnZrU3cKZoN6QkpgePX/4IbyULJi33riBQcv6Qt5
            P/78RxWcnjY24hlnd65o5T80A1vHtqjSw8LppJj7upmhegZjiEW6ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T02:44:24Z"
    mac: ENC[AES256_GCM,data:cxSPLpGNhTtBfTbCqxnV8doz8wEGJeXCrRMyTEh1R6lm0AguP9YFzFlcFLZPmF1L1JuKWfrAn0MDxkgPx/73SmIhww7TzhDNVSqJHVS3tLIZ6r0Ge5YGppKymBpPtQ5SlunmyOFlCy7REBdkwTWn7jT4JMncEvulnbbnTr2Zm5I=,iv:FMskMjqjWR59NgLJNW6L7NAr8YlhZ5vSIYi5KSSrYnA=,tag:XaxWFUTIPtB+xW/vRYCyGw==,type:str]
    version: 3.13.0
